eureka:
  instance:
    prefer-ip-address: true
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
       defaultZone: ${EUREKA_SERVER_ADDRESS:http://54.169.219.205:8761/eurka}
