eureka:
  instance:
    prefer-ip-address: true
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
       defaultZone: ${EUREKA_SERVER_ADDRESS:http://13.229.172.132:8761/eurka}
